#!/bin/bash
#PBS -q express
#PBS -l walltime=10:00:00,mem=5GB,wd,ncpus=8
#PBS -N publish
#PBS -joe
#PBS -P v45

module purge
module use /g/data3/hh5/public/modules
module load conda/analysis3-unstable

module list

set -x 

COSIMADIR=/g/data3/hh5/tmp/cosima
OUTPATH=/g/data1a/ua8/cosima-tmp/publish

#(cd mom_10; . README)
(cd mom_025; . README)
#(cd mom_01; . README)
